rootPageId: 1
websiteTitle: 'Ps14'
base: /
baseVariants:
  -
    base: 'https://ps14-typo3-dev.ddev.site/'
    condition: 'applicationContext == "Development"'
  -
    base: 'https://dev.ps14.de/'
    condition: 'applicationContext == "Production"'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /de/
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
    hreflang: de
    websiteTitle: ''
  -
    title: English
    enabled: true
    languageId: 1
    fallbackType: strict
    base: /en/
    typo3Language: default
    locale: en-GB.UTF-8
    navigationTitle: English
    hreflang: en
    direction: ''
    flag: gb
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=47'
routes:
  -
    route: /de/sitemap.xml
    type: uri
    source: 't3://page?type=1533906435'
  -
    route: /en/sitemap.xml
    type: uri
    source: 't3://page?type=1533906435'
  -
    route: robots.txt
    type: staticText
    content: |
      User-agent: *
      Disallow: /typo3/
      Disallow: /vendor/
      Disallow: /typo3_src/
      Sitemap: https://ps14-typo3-dev.ddev.site/de/sitemap.xml
      Sitemap: https://ps14-typo3-dev.ddev.site/en/sitemap.xml
dependencies:
  - foundation/meta